# Generated by Django 5.1.4 on 2025-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_userprofile_gender"),
        ("gift", "0004_alter_award_employee_name_delete_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="award",
            name="employee_name",
        ),
        migrations.AddField(
            model_name="award",
            name="employees",
            field=models.ManyToManyField(
                related_name="awards", to="authentication.userprofile"
            ),
        ),
    ]
