# Generated by Django 5.1.4 on 2025-07-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0005_remove_award_employee_name_award_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("employee_month", "Employee of the Month"),
                            ("employee_quarter", "Employee of the Quarter"),
                            ("top_reviews", "Top Google Reviews"),
                            ("sales_leader", "Sales Leader"),
                            ("most_improved", "Most Improved"),
                            ("crew_leader", "Crew Leader Spotlight"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="award",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="award",
            name="date_award",
            field=models.DateField(default="2025-03-03"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="award",
            name="date_saved",
            field=models.DateField(auto_now_add=True, default="2025-03-03"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="award",
            name="category",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gift.awardcategory",
            ),
        ),
    ]
