# Generated by Django 5.1.4 on 2025-07-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0006_awardcategory_alter_award_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("employee_month", "Employee of the Month"),
                    ("employee_quarter", "Employee of the Quarter"),
                    ("top_reviews", "Top Google Reviews"),
                    ("sales_leader", "Sales Leader"),
                    ("most_improved", "Most Improved"),
                    ("crew_leader", "Crew Leader Spotlight"),
                    ("gift_card", "Gift Card"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
