# Generated by Django 5.1.4 on 2025-07-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0007_alter_awardcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gift_card",
                to="gift.gift_card",
            ),
        ),
    ]
