# Generated by Django 5.1.4 on 2025-07-14 09:06

import django.core.files.storage
import gift.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0008_alter_award_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="employee_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=gift.models.award_photo_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="awardcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
