# Generated by Django 5.1.4 on 2025-07-14 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_userprofile_gender"),
        ("gift", "0009_award_employee_photo_alter_awardcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="date_award",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name="award",
            name="employees",
        ),
        migrations.AddField(
            model_name="award",
            name="employees",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="authentication.userprofile",
            ),
            preserve_default=False,
        ),
    ]
