# Generated by Django 5.1.4 on 2025-07-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0010_alter_award_date_award_remove_award_employees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="award",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gift.awardcategory",
            ),
        ),
    ]
