# Generated by Django 5.1.4 on 2025-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0011_alter_award_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="HallOfFameEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hall_of_fame_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
