# Generated by Django 5.1.4 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gift", "0012_halloffameentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardcategory",
            name="criteria",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="awardcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
