# Generated by Django 5.1.4 on 2025-07-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_userprofile_gender"),
        ("gift", "0013_awardcategory_criteria_awardcategory_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="halloffameentry",
            name="name",
        ),
        migrations.AddField(
            model_name="halloffameentry",
            name="employee",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hall_of_fame_entries",
                to="authentication.userprofile",
            ),
            preserve_default=False,
        ),
    ]
