# Generated by Django 5.1.4 on 2025-08-26 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "authentication",
            "0011_userprofile_is_admin_userprofile_is_employee_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Goal title", max_length=200)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("short_term", "Short-Term"),
                            ("long_term", "Long-Term"),
                        ],
                        default="short_term",
                        help_text="Type of goal",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the goal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Action plans for improvement", null=True
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Employee assigned to this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_goals",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Manager or senior management who created this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_goals",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
