# Generated by Django 5.1.4 on 2025-08-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0011_userprofile_is_admin_userprofile_is_employee_and_more",
        ),
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={
                "ordering": ["due_date", "title"],
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="completed_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="authentication.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_goals",
                to="authentication.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the goal"
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[("short_term", "Short-Term"), ("long_term", "Long-Term")],
                default="short_term",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Any notes or updates on the goal", null=True
            ),
        ),
    ]
