# Generated by Django 5.1.4 on 2025-09-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_alter_goal_options_goal_completed_at_goal_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(help_text="Detailed description of the goal"),
        ),
        migrations.AlterField(
            model_name="goal",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Due date for the goal", null=True
            ),
        ),
    ]
