# Generated by Django 5.1.4 on 2025-09-12 09:05

import goals.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_alter_goal_description_alter_goal_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the goal",
                validators=[goals.utils.validators.validate_goal_description_length],
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Due date for the goal",
                null=True,
                validators=[goals.utils.validators.validate_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=models.CharField(
                help_text="Goal title",
                max_length=200,
                validators=[goals.utils.validators.validate_goal_title_length],
            ),
        ),
    ]
