# Generated by Django 5.1.4 on 2025-04-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0004_remove_userprofile_gender"),
        ("vehicle", "0006_alter_dispatch_crew_leads_crew_role_delete_crewstaff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("pull", "Pulling Materials"),
                            ("return", "Returning Materials"),
                            ("order", "Ordering Materials"),
                        ],
                        max_length=10,
                    ),
                ),
                ("job_id", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("small_boxes", models.IntegerField(blank=True, default=0, null=True)),
                ("medium_boxes", models.IntegerField(blank=True, default=0, null=True)),
                ("large_boxes", models.IntegerField(blank=True, default=0, null=True)),
                ("xl_boxes", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "wardrobe_boxes",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("dish_boxes", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "singleface_protection",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("carpet_mask", models.IntegerField(blank=True, default=0, null=True)),
                ("paper_pads", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "packing_paper",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("tape", models.IntegerField(blank=True, default=0, null=True)),
                ("wine_boxes", models.IntegerField(blank=True, default=0, null=True)),
                ("stretch_wrap", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "tie_down_webbing",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "packing_peanuts",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("ram_board", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "mattress_bags",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "mirror_cartons",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("bubble_wrap", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "gondola_boxes",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("employee_signature", models.CharField(max_length=100)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "trailer_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_received", models.DateField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packaging_supplies.material",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userprofile",
                    ),
                ),
            ],
        ),
    ]
