# Generated by Django 5.1.4 on 2025-07-07 23:25

import django.core.files.storage
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_promotionalitem_created_at_vendor_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingphoto",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=marketing.models.marketing_photo_upload_to,
            ),
        ),
    ]
