# Generated by Django 5.1.4 on 2024-12-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Completed', max_length=20)),
                ('ipad', models.CharField(blank=True, max_length=50, null=True)),
                ('crew_leads', models.CharField(blank=True, max_length=100, null=True)),
                ('drivers', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_1', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_1', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_2', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_2', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_3', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_3', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_4', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_4', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('special_equipment_needed', models.CharField(blank=True, max_length=200, null=True)),
                ('special_equipment_status', models.CharField(blank=True, max_length=200, null=True)),
                ('speedy_inventory_account', models.CharField(blank=True, max_length=100, null=True)),
                ('speedy_inventory', models.CharField(blank=True, max_length=200, null=True)),
                ('labels_for_speedy_inventory', models.CharField(blank=True, max_length=200, null=True)),
                ('notes_dispatcher', models.TextField(blank=True, null=True)),
                ('submitted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('last_name_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_move', models.CharField(blank=True, max_length=100, null=True)),
                ('moved_before', models.BooleanField(blank=True, default=False, null=True)),
                ('moved_before_crew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_available', models.BooleanField(blank=True, default=False, null=True)),
                ('number_of_trucks', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_trailers', models.PositiveIntegerField(blank=True, null=True)),
                ('notes_order_detail', models.TextField(blank=True, null=True)),
                ('saved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('saved_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_feedback', models.TextField(blank=True, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.dispatch')),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='vehicle.order'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_move', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_name', models.CharField(blank=True, max_length=100, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ipad_number', models.CharField(blank=True, max_length=20, null=True)),
                ('materials', models.CharField(blank=True, max_length=200, null=True)),
                ('specialty_equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('equipment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('speedy_inventory_account', models.CharField(blank=True, max_length=100, null=True)),
                ('speedy_inventory', models.CharField(blank=True, max_length=100, null=True)),
                ('labels_for_speedy_inventory', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_leads', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_leads_drivers', models.CharField(blank=True, max_length=100, null=True)),
                ('drivers', models.CharField(blank=True, max_length=100, null=True)),
                ('master_user', models.CharField(blank=True, max_length=50, null=True)),
                ('master_password', models.CharField(blank=True, max_length=50, null=True)),
                ('order_user', models.CharField(blank=True, max_length=50, null=True)),
                ('order_password', models.CharField(blank=True, max_length=50, null=True)),
                ('availability_user', models.CharField(blank=True, max_length=50, null=True)),
                ('availability_password', models.CharField(blank=True, max_length=50, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(blank=True, choices=[('truck', 'Truck'), ('trailer', 'Trailer')], max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('condition_report', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('In Service', 'In Service'), ('Out of Service', 'Out of Service')], max_length=50, null=True)),
                ('estimated_back_in_service_date', models.DateField(blank=True, null=True)),
                ('back_in_service_date', models.DateField(blank=True, null=True)),
                ('date_saved', models.DateTimeField(auto_now_add=True, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
    ]
