# Generated by Django 5.1.4 on 2025-02-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_alter_onsite_inspection_crew_leader_and_more'),
        ('vehicle', '0005_alter_dispatch_crew_leads_alter_order_crew_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsite_inspection',
            name='crew_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='crew_leader_inspections', to='vehicle.crew'),
        ),
        migrations.AlterField(
            model_name='onsite_inspection',
            name='crew_members',
            field=models.ManyToManyField(blank=True, related_name='crew_member_inspections', to='vehicle.crew'),
        ),
    ]
