# Generated by Django 5.1.4 on 2025-06-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0003_alter_onsite_inspection_crew_leader_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnsiteInspectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="inspection_photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inspection.onsite_inspection",
                    ),
                ),
            ],
        ),
    ]
