# Generated by Django 5.1.4 on 2025-08-20 12:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspection", "0004_onsiteinspectionimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onsiteinspectionimage",
            name="image",
            field=models.ImageField(
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="inspection_photos/",
            ),
        ),
    ]
