# Generated by Django 5.1.4 on 2025-10-17 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communicationlog",
            name="week_end",
        ),
        migrations.RemoveField(
            model_name="communicationlog",
            name="week_start",
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="acknowledgment_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline for employee to acknowledge this log",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="event_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date when the event/incident occurred",
            ),
        ),
        migrations.AddField(
            model_name="communicationlog",
            name="requires_acknowledgment",
            field=models.BooleanField(
                default=True, help_text="Whether employee needs to acknowledge this log"
            ),
        ),
    ]
