# Generated by Django 5.1.4 on 2025-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_logresponse_viewed_by_senior"),
    ]

    operations = [
        migrations.AddField(
            model_name="logresponse",
            name="viewed_by_manager",
            field=models.BooleanField(
                default=False, help_text="Whether manager has viewed this response"
            ),
        ),
    ]
