# Generated by Django 5.1.4 on 2025-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("unisex", "Unisex")],
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("llc/field", "LLC/Field"),
                    ("llc/owner", "LLC/Owner"),
                    ("sales", "Sales"),
                    ("field", "Field"),
                    ("driver", "Driver"),
                    ("manager", "Manager"),
                    ("rwh", "RWH"),
                    ("technician", "Technician"),
                    ("admin", "Admin"),
                    ("warehouse", "Warehouse"),
                    ("mover", "Mover"),
                    ("technician", "Technician"),
                    ("customers- per trevor", "Customers- Per Trevor"),
                ],
                default="driver",
                max_length=50,
            ),
        ),
    ]
