# Generated by Django 5.1.4 on 2025-02-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_gender_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="gender",
        ),
    ]
