# Generated by Django 5.1.4 on 2025-07-20 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0006_userprofile_designation_userprofile_favourite_quote_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="favourite_quote",
            field=models.TextField(
                blank=True, help_text="Your favorite inspirational quote"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="hobbies",
            field=models.TextField(
                blank=True, help_text="Optional: List hobbies comma-separated"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: +1234567890",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+1234567890'. Up to 15 digits allowed.",
                        regex="^\\+?\\d{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("llc/field", "LLC/Field"),
                    ("llc/owner", "LLC/Owner"),
                    ("sales", "Sales"),
                    ("field", "Field"),
                    ("driver", "Driver"),
                    ("manager", "Manager"),
                    ("rwh", "RWH"),
                    ("technician", "Technician"),
                    ("admin", "Admin"),
                    ("warehouse", "Warehouse"),
                    ("mover", "Mover"),
                    ("customers- per trevor", "Customers- Per Trevor"),
                ],
                default="driver",
                max_length=50,
            ),
        ),
    ]
