# Generated by Django 5.1.4 on 2025-07-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_userprofile_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="designation",
        ),
    ]
