# Generated by Django 5.1.4 on 2025-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_remove_userprofile_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_employee",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_senior_management",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("llc/field", "LLC/Field"),
                    ("llc/owner", "LLC/Owner"),
                    ("sales", "Sales"),
                    ("field", "Field"),
                    ("driver", "Driver"),
                    ("manager", "Manager"),
                    ("rwh", "RWH"),
                    ("technician", "Technician"),
                    ("admin", "Admin"),
                    ("warehouse", "Warehouse"),
                    ("mover", "Mover"),
                    ("customers- per trevor", "Customers- Per Trevor"),
                    ("vp", "VP"),
                    ("ceo", "CEO"),
                ],
                default="driver",
                max_length=50,
            ),
        ),
    ]
