# Generated by Django 5.1.4 on 2025-08-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_department_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="department_roles",
                to="authentication.userprofile",
            ),
        ),
    ]
