# Generated by Django 5.1.4 on 2025-10-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_department_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly identifier (not editable)",
                max_length=100,
                null=True,
            ),
        ),
    ]
