# Generated by Django 5.1.4 on 2025-10-02 10:11

from django.db import migrations
from django.utils.text import slugify


def populate_department_slugs(apps, schema_editor):
    """Populate department slugs from titles."""
    Department = apps.get_model('authentication', 'Department')
    
    for dept in Department.objects.all():
        if not dept.slug:  # Only populate if slug is empty
            dept.slug = slugify(dept.title)
            dept.save()


def reverse_populate_department_slugs(apps, schema_editor):
    """Reverse operation - clear slugs."""
    Department = apps.get_model('authentication', 'Department')
    Department.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_department_slug"),
    ]

    operations = [
        migrations.RunPython(populate_department_slugs, reverse_populate_department_slugs),
    ]
