# Generated by Django 5.1.4 on 2025-08-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_department_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Goal title", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the goal"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("target_date", models.DateField(help_text="Target completion date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="Employee assigned to this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_goals",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Manager or senior management who created this goal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_goals",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department this goal belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_goals",
                        to="authentication.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["-created_at"],
            },
        ),
    ]
