# Generated by Django 5.1.4 on 2025-10-08 11:34

from django.db import migrations
from django.utils.text import slugify


def normalize_department_title(title):
    """
    Normalize department title for slug generation.
    Removes common suffixes like 'Department', 'Dept', 'Dep', etc.
    """
    if not title:
        return ""
    
    # Convert to lowercase for case-insensitive matching
    normalized = title.lower().strip()
    
    # Remove common department suffixes
    suffixes = [
        'department',
        'dept',
        'dep',
        'dpt',
    ]
    
    for suffix in suffixes:
        # Remove suffix with or without preceding space/dash
        if normalized.endswith(f' {suffix}'):
            normalized = normalized[:-len(suffix)-1].strip()
        elif normalized.endswith(f'-{suffix}'):
            normalized = normalized[:-len(suffix)-1].strip()
        elif normalized.endswith(suffix):
            normalized = normalized[:-len(suffix)].strip()
    
    return normalized


def normalize_existing_slugs(apps, schema_editor):
    """Update all department slugs to use normalized titles."""
    Department = apps.get_model('authentication', 'Department')
    
    for dept in Department.objects.all():
        normalized_title = normalize_department_title(dept.title)
        new_slug = slugify(normalized_title)
        
        # Only update if slug has changed
        if dept.slug != new_slug:
            dept.slug = new_slug
            dept.save(update_fields=['slug'])


def reverse_normalize_slugs(apps, schema_editor):
    """Reverse operation - restore original slugs from titles."""
    Department = apps.get_model('authentication', 'Department')
    
    for dept in Department.objects.all():
        dept.slug = slugify(dept.title)
        dept.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_auto_20251002_1011"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_slugs, reverse_normalize_slugs),
    ]
