# Generated by Django 5.1.4 on 2025-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[("short_term", "Short-Term"), ("long_term", "Long-Term")],
                default="short_term",
                help_text="Type of goal",
                max_length=20,
            ),
        ),
    ]
