# Generated by Django 5.1.4 on 2025-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_goal_goal_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="department",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="status",
        ),
        migrations.RemoveField(
            model_name="goal",
            name="target_date",
        ),
        migrations.AlterField(
            model_name="goal",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Action plans for improvement", null=True
            ),
        ),
    ]
