# Generated by Django 5.1.4 on 2025-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_goal_department_remove_goal_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
