# Generated by Django 5.1.4 on 2025-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_alter_department_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(
                help_text="Use one of: sales, accounting, claims, it, operations, warehouse, drivers (determines evaluation questions)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
