# Generated by Django 5.1.4 on 2025-10-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_alter_department_slug_departmentquiz_quizattempt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentquiz",
            options={
                "ordering": ["audience", "order"],
                "verbose_name": "Department Quiz Question",
                "verbose_name_plural": "Department Quiz Questions",
            },
        ),
        migrations.AddField(
            model_name="departmentquiz",
            name="audience",
            field=models.CharField(
                choices=[("employee", "Employee"), ("manager", "Manager")],
                default="employee",
                help_text="Employee or Manager quiz",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="quiz_type",
            field=models.CharField(
                choices=[("employee", "Employee"), ("manager", "Manager")],
                default="employee",
                max_length=10,
            ),
        ),
    ]
