from django.core.management.base import BaseCommand
from inventory_app.models import UniformCatalog  

class Command(BaseCommand):
    help = 'Seeds uniform catalog data into the database'

    def handle(self, *args, **kwargs):
        uniform_data = [
            # Uniform Name, Category, Gender, Minimum Stock Level
            ("S Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("M Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("L Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("XL Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("2XL Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("3XL Grey Marbled Short Sleeve", "Shirts", "Unisex", 1),
            ("S Purple Short Sleeve", "Shirts", "Female", 1),
            ("M Purple Short Sleeve", "Shirts", "Female", 1),
            ("L Purple Short Sleeve", "Shirts", "Female", 1),
            ("XL Purple Short Sleeve", "Shirts", "Female", 1),
            ("2XL Purple Short Sleeve", "Shirts", "Female", 1),
            ("S Black Short Sleeve", "Shirts", "Female", 1),
            ("M Black Short Sleeve", "Shirts", "Female", 1),
            ("L Black Short Sleeve", "Shirts", "Female", 1),
            ("XL Black Short Sleeve", "Shirts", "Female", 1),
            ("2XL Black Short Sleeve", "Shirts", "Unisex", 1),
            ("3XL Black Short Sleeve", "Shirts", "Unisex", 1),
            ("XL Short Sleeve Misc.", "Shirts", "Unisex", 1),
            ("S Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("M Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("L Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("XL Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("2XL Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("3XL Charcoal Long Sleeve", "Shirts", "Unisex", 1),
            ("S Charcoal Breast Cancer", "Branding Items", "Unisex", 1),
            ("M Charcoal Breast Cancer", "Branding Items", "Unisex", 1),
            ("L Charcoal Breast Cancer", "Branding Items", "Unisex", 1),
            ("XL Charcoal Breast Cancer", "Branding Items", "Unisex", 1),
            ("3XL Charcoal Breast Cancer", "Branding Items", "Unisex", 1),
            ("XS Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("S Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("M Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("L Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("XL Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("2XL Light Grey Breast Cancer", "Branding Items", "Female", 1),
            ("S Grey Sweater", "Shirts", "Unisex", 1),
            ("M Grey Sweater", "Shirts", "Unisex", 1),
            ("L Grey Sweater", "Shirts", "Unisex", 1),
            ("XL Grey Sweater", "Shirts", "Unisex", 1),
            ("2XL Grey Sweater", "Shirts", "Unisex", 1),
            ("3XL Grey Sweater", "Shirts", "Unisex", 1),
            ("S Black Shorts", "Shorts", "Male", 1),
            ("M Black Shorts", "Shorts", "Male", 1),
            ("L Black Shorts", "Shorts", "Male", 1),
            ("XL Black Shorts", "Shorts", "Male", 1),
            ("2XL Black Shorts", "Shorts", "Male", 1),
            ("3XL Black Shorts", "Shorts", "Male", 1),
            ("S Sweatpants", "Pants", "Male", 1),
            ("M Sweatpants", "Pants", "Male", 1),
            ("L Sweatpants", "Pants", "Male", 1),
            ("XL Sweatpants", "Pants", "Male", 1),
            ("2XL Sweatpants", "Pants", "Male", 1),
            ("S Hoodie", "Seasonal Wear", "Unisex", 1),
            ("M Hoodie", "Seasonal Wear", "Unisex", 1),
            ("L Hoodie", "Seasonal Wear", "Unisex", 1),
            ("XL Hoodie", "Seasonal Wear", "Unisex", 1),
            ("XXL Hoodie", "Seasonal Wear", "Unisex", 1),
            ("XXXL Hoodie", "Seasonal Wear", "Unisex", 1),
            ("S MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("M MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("L MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("XL MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("2XL MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("3XL MGMT Hoodie", "Seasonal Wear", "Unisex", 1),
            ("Cooling Gaiters", "Accessories", "Male", 1),
            ("Grey Cooling Gaiters", "Accessories", "Male", 1),
            ("Rain Ponchos", "Accessories", "Unisex", 1),
            ("Rain Suits", "Outerwear", "Unisex", 1),
            ("S Rain Pants", "Outerwear", "Unisex", 1),
            ("M Rain Pants", "Outerwear", "Unisex", 1),
            ("L Rain Pants", "Outerwear", "Unisex", 1),
            ("XL Rain Pants", "Outerwear", "Unisex", 1),
            ("2XL Rain Pants", "Outerwear", "Unisex", 1),
            ("3XL Rain Pants", "Outerwear", "Unisex", 1),
            ("S Rain Jackets", "Outerwear", "Unisex", 1),
            ("M Rain Jackets", "Outerwear", "Unisex", 1),
            ("L Rain Jackets", "Outerwear", "Unisex", 1),
            ("XL Rain Jackets", "Outerwear", "Unisex", 1),
            ("2XL Rain Jackets", "Outerwear", "Unisex", 1),
            ("3XL Rain Jackets", "Outerwear", "Unisex", 1),
            ("Golf Camping Coat", "Seasonal Wear", "Unisex", 1),
            ("Heated Jacket", "Seasonal Wear", "Male", 1),
            ("Beanie", "Headwear", "Unisex", 1),
            ("Hat (B)", "Headwear", "Unisex", 1),
            ("Hat (WB)", "Headwear", "Unisex", 1),
            ("Cooling Hats", "Headwear", "Unisex", 1),
            ("Belts", "Accessories", "Male", 1),
            ("Orange Safety Vests", "Accessories", "Unisex", 1),
            ("Pink Safety Vests", "Accessories", "Unisex", 1),
            ("S Pants", "Pants", "Male", 1),
            ("M Pants", "Pants", "Male", 1),
            ("L Pants", "Pants", "Male", 1),
            ("XL Pants", "Pants", "Male", 1),
            ("2XL Pants", "Pants", "Male", 1),
            ("3XL Pants", "Pants", "Male", 1),
            ("XS Polos-Male", "Shirts", "Male", 1),
            ("S Polos-Male", "Shirts", "Male", 1),
            ("M Polos-Male", "Shirts", "Male", 1),
            ("L Polos-Male", "Shirts", "Male", 1),
            ("XL Polos-Male", "Shirts", "Male", 1),
            ("2XL Polos-Male", "Shirts", "Male", 1),
            ("3XL Polos-Male", "Shirts", "Male", 1),
            ("XS Polos-Female", "Shirts", "Female", 1),
            ("S Polos-Female", "Shirts", "Female", 1),
            ("M Polos-Female", "Shirts", "Female", 1),
            ("L Polos-Female", "Shirts", "Female", 1),
            ("XL Polos-Female", "Shirts", "Female", 1),
            ("2XL Polos-Female", "Shirts", "Female", 1),
            ("3XL Polos-Female", "Shirts", "Female", 1),
            ("S Jacket-Male", "Outerwear", "Male", 1),
            ("M Jacket-Male", "Outerwear", "Male", 1),
            ("L Jacket-Male", "Outerwear", "Male", 1),
            ("XL Jacket-Male", "Outerwear", "Male", 1),
            ("2XL Jacket-Male", "Outerwear", "Male", 1),
            ("3XL Jacket-Male", "Outerwear", "Male", 1),
            ("S Jacket-Female", "Outerwear", "Female", 1),
            ("M Jacket-Female", "Outerwear", "Female", 1),
            ("L Jacket-Female", "Outerwear", "Female", 1),
            ("XL Jacket-Female", "Outerwear", "Female", 1),
            ("2XL Jacket-Female", "Outerwear", "Female", 1),
            ("3XL Jacket-Female", "Outerwear", "Female", 1),
            ("39 shoes", "Shoes", "Unisex", 1),
            ("40 shoes", "Shoes", "Unisex", 1),
            ("41 shoes", "Shoes", "Unisex", 1),
            ("42 shoes", "Shoes", "Unisex", 1),
            ("43 shoes", "Shoes", "Unisex", 1),
            ("44 shoes", "Shoes", "Unisex", 1),
            ("45 shoes", "Shoes", "Unisex", 1),
            ("46 shoes", "Shoes", "Unisex", 1),
            ("47 shoes", "Shoes", "Unisex", 1),
            ("48 shoes", "Shoes", "Unisex", 1),
            ("Golf Polo Jackets - Light Blue", "Jackets", "Female", 3),
            ("S Golf Polo Jackets - Light Blue", "Jackets", "Female", 1),
            ("XL Golf Polo Jackets - Light Blue", "Jacket", "Female", 2),
            ("S Golf Polo Jackets - Dark Blue", "Jacket", "Female", 1),
            ("XL Golf Polo Jackets - Dark Blue", "Jacket", "Female", 2),
            ("S Golf Polo Jackets - Grey", "Jacket", "Female", 1),
            ("XLGolf Polo Jackets - Grey", "Jacket", "Female", 2),
            ("S Golf Polo Jackets - Black", "Jacket", "Female", 1),
            ("XL Golf Polo Jackets - Black", "Jacket", "Female", 2),
        ]

        # Prepare the list of UniformCatalog objects
        uniforms_to_create = [
            UniformCatalog(name=uniform[0], category=uniform[1], gender=uniform[2], minimum_stock_level=uniform[3])
            for uniform in uniform_data
        ]

        # Bulk create the uniform entries in the database
        UniformCatalog.objects.bulk_create(uniforms_to_create)

        self.stdout.write(self.style.SUCCESS("✅ Uniform catalog data seeded successfully!"))
