# Generated by Django 5.1.4 on 2025-01-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_alter_employee_designation_alter_employee_name_and_more'),
        ('inventory_app', '0003_alter_employee_designation_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniformCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], max_length=20, null=True)),
                ('minimum_stock_level', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryassignment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='inventoryassignment',
            name='uniform',
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='minimum_stock',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='not_returned',
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_bought',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_stock',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='disposed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='in_use',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='new_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='return_to_supplier',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='used_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='UniformAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Returned', 'Returned')], max_length=20, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gift.employee')),
                ('uniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.uniformcatalog')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('Purchase', 'Purchase'), ('Return to Supplier', 'Return to Supplier'), ('Dispose', 'Dispose')], max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uniform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.uniformcatalog')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='uniform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.uniformcatalog'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='InventoryAssignment',
        ),
    ]
