# Generated by Django 5.1.4 on 2025-02-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_role'),
        ('inventory_app', '0004_uniformcatalog_remove_inventoryassignment_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformassignment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
