# Generated by Django 5.1.4 on 2025-01-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('station', '0003_onsite_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsite_inspection',
            name='crew_members',
        ),
        migrations.AddField(
            model_name='onsite_inspection',
            name='crew_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='crew_member_inspections', to='authentication.userprofile'),
        ),
    ]
